apiVersion: v1
kind: Secret
metadata:
  name: vt-credentials
  namespace: malware-analysis
type: Opaque
stringData:
  REDIS_URL: "redis://redis:6379"
  RESULTS_PATH: "/data/results"
  SANDBOX_URL: "http://192.168.122.2:9000"
  YARA_DIR_PATH: "/yara-rules"