apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dynamic
  namespace: malware-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-dynamic
  template:
    metadata:
      labels:
        app: worker-dynamic
    spec:
      containers:
        - name: worker-dynamic
          image: dockerhubmalware/malware-worker-dynamic:v1.0.6
          # Injection de toutes les variables d'environnement depuis le secret
          envFrom:
            - secretRef:
                name: vt-credentials
          env:
            - name: SANDBOX_URL
              value: "http://sandbox-controller:9000"
          volumeMounts:
            - name: results
              mountPath: /data/results
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: results-pvc
