apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: malware-analysis
resources:
  - namespace.yaml
  - configmap-yara.yaml
  - secrets.yaml
  - pvc.yaml
  - redis.yaml
  - api-deployment.yaml
  - worker-static-deployment.yaml
  - worker-dynamic-deployment.yaml
  - sandbox-controller-deployment.yaml
