version: 2
ethernets:
  eth0:
    match:
      macaddress: "52:54:00:00:00:10"
    set-name: eth0
    dhcp4: no
    addresses:
      - 192.168.122.2/24

  eth1:
    match:
      macaddress: "52:54:00:00:00:20"
    set-name: eth1
    dhcp4: yes
    gateway4: 192.168.123.1