#cloud-config
hostname: k3s
ssh_pwauth: True
disable_root: true
packages:
  - curl
  - sudo
  - git
  - iptables-persistent
keyboard:
  layout: fr
  variant: ""
users:
  - name: k3s
    groups: sudo
    shell: /bin/bash
    passwd: "$6$8HnNkXiciaai5RDJ$6sEe5zHc.uMcs3S62tamFUWDPY/Foey/krrTxPqRsLf6.WgE9IY/bs0fd2wEiw39z4qWzcgTetNVBr3VRiq8n."
    lock_passwd: false
    ssh_authorized_keys:
      - __SSH_KEY__

write_files:
  - path: /etc/systemd/system/fix-argocd.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Fix argocd-repo-server after boot
      After=k3s.service
      Wants=k3s.service

      [Service]
      Type=oneshot
      Environment=KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      ExecStart=/bin/bash -c 'until /usr/local/bin/kubectl get nodes --request-timeout=5s >/dev/null 2>&1; do echo "Attente k3s..."; sleep 5; done; sleep 10; /usr/local/bin/kubectl rollout restart deployment argocd-repo-server -n argocd'
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Installer k3s (single-node)
  - curl -sfL https://get.k3s.io | sh -
  # Installer kubectl
  - curl -LO https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p /home/k3s/.kube
  - cp /etc/rancher/k3s/k3s.yaml /home/k3s/.kube/config
  - chown -R k3s:k3s /home/k3s/.kube
  # Attendre que tout démarre
  - |
    until k3s kubectl get nodes >/dev/null 2>&1; do
      sleep 5
    done
  # Installer ArgoCD dans le cluster
  - k3s kubectl create namespace argocd || true
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - cd /home/k3s
  - k3s kubectl create namespace malware-analysis --dry-run=client -o yaml | k3s kubectl apply -f -
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/na-teag/PFE/refs/heads/main/infra/argocd/malware-analysis-app.yaml
  - |
    k3s kubectl patch svc argocd-server -n argocd --type=merge -p '{"spec":{"type":"NodePort"}}'
  - systemctl daemon-reload
  - systemctl enable fix-argocd.service

