#cloud-config
hostname: k3s
ssh_pwauth: True
packages:
  - curl
  - sudo
  - git
keyboard:
  layout: fr
  variant: ""
users:
  - name: k3s
    groups: sudo
    shell: /bin/bash
    passwd: "$6$8HnNkXiciaai5RDJ$6sEe5zHc.uMcs3S62tamFUWDPY/Foey/krrTxPqRsLf6.WgE9IY/bs0fd2wEiw39z4qWzcgTetNVBr3VRiq8n."
    lock_passwd: false
    ssh_authorized_keys:
      - __SSH_KEY__

runcmd:
  # Installer k3s (single-node)
  - curl -sfL https://get.k3s.io | sh -
  # Installer kubectl
  - curl -LO https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p /home/k3s/.kube
  - cp /etc/rancher/k3s/k3s.yaml /home/k3s/.kube/config
  - chown -R k3s:k3s /home/k3s/.kube
  # Attendre que tout démarre
  - |
    until k3s kubectl get nodes >/dev/null 2>&1; do
      sleep 5
    done
  # Installer ArgoCD dans le cluster
  - k3s kubectl create namespace argocd || true
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - cd /home/k3s
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/na-teag/PFE/refs/heads/main/infra/argocd/malware-analysis-app.yaml
  - |
    k3s kubectl patch svc argocd-server -n argocd -p '{"spec":{"type":"LoadBalancer"}}'